// This file is part of InfiniteSky.
// Copyright (c) InfiniteSky Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder
vms('SkillInfo', [], function(){
  var skillSchema = mongoose.Schema({
    ID: { type: Number, unique: true, index: true, default: 0 },
    Name: String,
    Category: Number,
    // unk0: Number,
    SpriteStartID: Number,
    Clan: Number,
    Weapon: Number,
    Description1: String,
    Description2: String,
    Description3: String,
    // unk1: Number,
    // unk2: Number,
    // unk3: Number,
    // unk4: Number,
    // unk5: Number,
    // unk6: Number,
    // unk7: Number,
    // unk8: Number,
    // unk9: Number,
    // unk10: Number,
    // unk11: Number,
    // unk12: Number,
    // unk13: Number,
    // unk14: Number,
    // unk15: Number,
    // unk16: Number,
    // unk17: Number,
    // unk18: Number,
    // unk19: Number,
    // unk20: Number,
    // unk21: Number,
    // unk22: Number,
    // unk23: Number,
    // unk24: Number,
    // unk25: Number,
    // unk26: Number,
    // unk27: Number,
    // unk28: Number,
    // unk29: Number,
    // unk30: Number,
    // unk31: Number,
    // unk32: Number,
    // unk33: Number,
    ChiUsage: Number,
    // unk33: Number,
    // unk66: Number,
    // unk99: Number,
    // unk132: Number,
    // unk165: Number,
    // unk198: Number,
    // unk231: Number,
    // unk264: Number,
    // unk297: Number,
    // unk330: Number,
    // unk363: Number,
    // unk396: Number,
    // unk429: Number,
    // unk462: Number,
    // unk495: Number,
    // unk528: Number,
    // unk561: Number,
    // unk594: Number,
    // unk627: Number,
    // unk660: Number,
    // unk693: Number,
    // unk726: Number,
    // unk759: Number,
    // unk792: Number,
    // unk825: Number,
    // unk858: Number,
    // unk891: Number,
    // unk924: Number,
    // unk957: Number,
    // unk990: Number,
    // unk1023: Number,
    // unk1056: Number,
    // unk1089: Number,
    // unk1122: Number,
    // unk1155: Number,
    // unk1188: Number,
    // unk1221: Number,
    // unk1254: Number,
    // unk1287: Number,
    // unk1320: Number,
    // unk1353: Number,
    // unk1386: Number,
    // unk1419: Number,
    // unk1452: Number,
    // unk1485: Number,
    // unk1518: Number,
    // unk1551: Number,
    // unk1584: Number,
    // unk1617: Number,
    // unk1650: Number,
    // unk1683: Number,
    // unk1716: Number,
    // unk1749: Number,
    // unk1782: Number,
    // unk1815: Number,
    // unk1848: Number,
    // unk1881: Number,
    PointsToLearn: Number,
    MaxSkillLevel: Number,
    // unk2000: Number,
    ModifiersStart: Object,
    ModifiersEnd: Object
  });

  skillSchema.methods.isUsedByClan = function(clan){
    return this.Clan === 1 || this.Clan === (clan+2);
  };

  delete mongoose.models['skill'];
  var SkillInfo = db.mongoose.model('skill', skillSchema);

  SkillInfo.findById = function(id, callback){
		db.Skill.findOne({
			ID: id
		}, callback);
	};

  db.Skill = SkillInfo;
});
